name: Website Preview Deployment

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  website-preview-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_EXAMPLES_PAT }}
          message: |
            ⏳ Deploying to https://github-action-examples-pr${{ github.event.number }}.surge.sh

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1.7.10
        with:
          working-directory: './'
          useLockFile: false

      - name: Build Website
        run: npm run build

      - name: Deploy Website
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'github-action-examples-pr${{ github.event.number }}.surge.sh'
          project: 'dist'
          login: ${{ secrets.GH_ACTION_SURGE_LOGIN }}
          token: ${{ secrets.GH_ACTION_SURGE_TOKEN }}

      - name: Comment Preview URL
        if: ${{ success() }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_EXAMPLES_PAT }}
          message: |
            Preview URL: https://github-action-examples-pr${{ github.event.number }}.surge.sh
